name: Lint Scripts

on: [push, pull_request]

jobs:
  powercli-lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: PowerShell Lint
        run: echo "PowerShell linter would run here"

  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Python Lint
        run: echo "Python linter would run here"
